### ISSUE TITLE
should be used conda install -c conda-forge catboost ?

### ISSUE THREAD

**Issue by Sandy4321** [conda-forge/catboost-feedstock#2]
Issue:
what actaul comand should be to install catboost
I see this recomendation 
conda install -c conda-forge catboost
from 
https://stackoverflow.com/questions/45165532/how-to-install-yandex-catboost-on-anaconda-x64
but on this website, I see other instructions to use channel? 
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by Sandy4321** [comment]
this question about  Windows 10 computer

**Comment by sab** [comment]
Both commands should work fine and install latest catboost version (at the moment 0.9.1.1).

> -c conda-forge
This parameter specifies channel
