### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/catboost-feedstock#80]
Upstream [`setup.py`](https://github.com/catboost/catboost/blob/10767543d83f880b15c039a9366deb6c6eb5aa67/catboost/python-package/setup.py#L296-L308) lists `graphviz` and `plotly` in `install_requires`. Is there a reason they're not listed in the recipe here? Their absence causes `pip check` to fail on things depending on `catboost`.

**Comment by HeavyTony2** [comment]
Fixed https://github.com/conda-forge/catboost-feedstock/pull/82
